### ISSUE TITLE
Issue when not use gripper in simulation

### ISSUE THREAD

**Issue by engineerkong** [NiryoRobotics/ned_ros#14]
Hi all,

I faced a problem when I run `roslaunch niryo_robot_bringup desktop_gazebo_simulation.launch ` to simulate but set the argument "gripper_n_camera" to be "false". I suppose niryo ros should have the option for not using gripper, but there are many errors coming, for example:

> [ WARN] [1686921438.655896157]: Group 'tool' is empty.
> [ERROR] [1686922342.440985, 1.062000]: Failed to load gazebo_tool_commander
> [ WARN] [1686921438.656475779]: Link 'base_gripper_1' is not known to URDF. Cannot disable collisons.
> [ERROR] [1686921438.652779967]: Link 'base_gripper_1' declared as part of group 'tool' is not known to the URDF
> [INFO] [1686925023.673470, 20.134000]: State Publisher - Failed to get TF base_link -> TCP

How could I deal with this problem? It will be very nice to have some answers from you. Thank you!

**Comment by jmottier-niryo** [comment]
Hi, the gazebo simulation has some known issues.
As a workaround, you could try to use the rviz simulation instead, which should work better.
`roslaunch niryo_robot_bringup desktop_rviz_simulation.launch hardware_version:=ned2`
