### ISSUE TITLE
Niryo Git Repo and Matlab

### ISSUE THREAD

**Issue by saftp** [NiryoRobotics/ned_ros#15]
When you using this GitRepo and trying to run it with the Matlab ROS Toolbox you constantly getting errors. Not matter what Matlab Version, Python or Cmake Version.

Reason is the following file:
niryo_robot_status\msg\RobotStatus.msg

The Constant ROBOT_MOTOR is defined twice. You have to delete one. 
If would be good to change that in this Repo as well.

Thanks and Regards
Patrick

**Comment by jmottier-niryo** [comment]
Hello, thank you for your feedback. This issue has been resolved since the v5.0.0
