### ISSUE TITLE
Problem to connect to the wifi

### ISSUE THREAD

**Issue by fabiocyro** [NiryoRobotics/ned_ros#16]
Hello everyone!

I am trying to connect my Ned 2 to the wifi network and after typing the SSID, password and clicking on connect I am getting this error:

"Can't process command the wifi client is not started"

The network is well configured, there are other devices connected.

Any suggestions?

Thanks in advance!

**Comment by jmottier-niryo** [comment]
Hi, can you give me following information ?
- Robot type (Ned/Ned2)
- Robot version
- Niryo Studio version
