### ISSUE TITLE
Redefine in niryo_robot_status/msg/RobotStatus.msg

### ISSUE THREAD

**Issue by jc-sz** [NiryoRobotics/ned_ros#18]
I am observing two `REBOOT_MOTOR` in niryo_robot_status/msg/RobotStatus.msg.
> line 10: int8 REBOOT_MOTOR=2
> line 21: int8 REBOOT_MOTOR=13

Is there a typo here?

**Comment by jmottier-niryo** [comment]
Thank you for your feedback.
Indeed, it seems that the assignment at the line 10 has no effect since it is overwritten at line 21.
This will be fixed in the next update.
