### ISSUE TITLE
joint length of robot arm

### ISSUE THREAD

**Issue by MouseRun** [NiryoRobotics/ned_ros#23]
Where can I find the joint lengths of niryo ned robotic arms?

**Comment by jmottier-niryo** [comment]
Hi, you can use the description files of the robot, either by using the [URDF](../blob/master/niryo_robot_description/urdf/ned2/niryo_ned2.urdf.xacro) or at runtime by getting the value of the rosparam `/robot_description`

**Comment by MouseRun** [comment]
Sorry, there's something wrong with what I'm describing. I think it's the length of the link connecting the joints. Where can I find it?

**Comment by jmottier-niryo** [comment]
Sorry, I'm not sure to understand what you want
Everything related to the static geometry of the robot is in the URDF files
