### ISSUE TITLE
Need some suggestions to use Niryo Ned with ROS2?

### ISSUE THREAD

**Issue by nqduy35** [NiryoRobotics/ned_ros#7]
Hello, do you plan to develop a ROS2 version for Niryo Ned? I tried to control and connect Niryo Ned with other robots running ROS2. Do you have any suggestions?

**Comment by ValentinPitre** [comment]
We are thinking about it. But I can't confirm anything. 

A simple way to interconnect a ros2 robot with a Ned is to use the python api [pyniryo](https://docs.niryo.com/en/index.html) to control the robot remotely.

**Comment by codesim** [comment]
Any news on this?
Using pyniryo, I would have to build a ROS2 node defining some glue logic between the pyniryo API and ROS2 services/messages.  Do you plan to make this easier by providing native use of ROS2?

**Comment by Jpl-niryo** [comment]
Hi,

At some point we will transition over to ROS2 but our latest update will first be to switch over to ROS Noetic. It is hard to tell when we will move over to a native use of ROS unfortunately

**Comment by nqduy35** [comment]
Thank you for the information. It is also very useful if the Niryo team could migrate the code from ROS 1 to ROS 2 using ros1_bridge (https://github.com/ros2/ros1_bridge)
